config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/ do
    as :user do
      post "/users", to: "registrations#create"
    end
    resources :inscriptions, only: [:create, :destroy]
    resources :events, only: [:create, :edit, :update, :destroy]
    devise_for :users, controllers: {:registrations => "registrations"}
    root to: 'pages#home'
    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  end
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :club
  belongs_to :user

  has_many :inscriptions, dependent: :destroy

  validates :date, presence: true
  validates :period, presence: true
  validates :start_time, presence: true
  validates :categories, presence: true
  validates :location, presence: true
  validates :contact, presence: true
  validates :club_id, presence: true
  validates :user_id, presence: true
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:edit, :update, :destroy]

  def create
    @event = Event.new(date: params[:date], 
      period: params[:period], 
      start_time: params[:start_time], 
      club_id: params[:club_id], 
      is_outdoor: params[:is_outdoor],
      location: params[:location],
      contact: params[:contact],
      other_informations: params[:other_informations]
    )

    categories_h = {}
    Category.all.each do |category|
      if params["category-#{category.id}"]
        categories_h[category.id] = { "places_left": params["total_places-#{category.id}"].to_i, "total_places": params["total_places-#{category.id}"].to_i }
      else 
        categories_h[category.id] = { "places_left": 0, "total_places": 0 }
      end
    end

    @event.categories = categories_h
    @event.user = current_user
    
    @event.is_tournament_open = true

    authorize @event

    if @event.save!
      redirect_to root_path
    else
      render :new
    end
  end

  def edit
    @categories = []
    Category.all.each do |category|
      @categories << "#{t 'underShortened'}#{category.age} #{category.level}#{category.gender.capitalize if category.gender == 'girls'}".strip
    end

    @open = t 'open'
    @close = t 'close'
    
    @indoor = t 'indoor'
    @outdoor = t 'outdoor'

    @morning = t 'morning'
    @afternoon = t 'afternoon'
    @fullDay = t 'fullDay'
  end

  def update
    @event.date = Time.new(params[:event]["date(1i)"], params[:event]["date(2i)"], params[:event]["date(3i)"]).strftime("%F")
    @event.period = params[:event][:period]
    @event.start_time = Time.new(2000, 1, 1, params[:event]["start_time(4i)"], params[:event]["start_time(5i)"]).strftime("%H:%M")
    @event.location = params[:event][:location]
    @event.contact = params[:event][:contact]
    @event.is_tournament_open = params[:event][:is_tournament_open]
    @event.is_outdoor = params[:event][:is_outdoor]
    @event.other_informations = params[:event][:other_informations]
    @event.user = current_user

    
    categories_h = {}
    Category.all.each do |category|
      if params["category-#{category.id}"]
        categories_h[category.id] = { "places_left": @event[:categories][category.id.to_s]["places_left"].to_i + (params["total_places-#{category.id}"].to_i - @event[:categories][category.id.to_s]["total_places"].to_i), "total_places": params["total_places-#{category.id}"].to_i }
      else 
        categories_h[category.id] = { "places_left": 0, "total_places": 0 }
      end
    end

    @event.categories = categories_h

    if @event.save!
      redirect_to root_path
    else
      render :new
    end
  end

  def destroy
    @event.destroy

    redirect_to root_path
  end

  private

  def set_event
    @event = Event.find(params[:id])

    authorize @event
  end

end

app/views/events/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-6 col-sm-offset-6 mx-auto">
      <div class="form-login">
        <h1><%= t 'editATournament' %></h2>
        <%= simple_form_for @event,
          wrapper: :horizontal_form,
          wrapper_mappings: {
            boolean:       :horizontal_boolean,
            check_boxes:   :horizontal_collection,
            date:          :horizontal_multi_select,
            datetime:      :horizontal_multi_select,
            file:          :horizontal_file,
            radio_buttons: :horizontal_collection,
            range:         :horizontal_range,
            time:          :horizontal_multi_select
          } do |f| %>

          <%= f.error_notification %>

          <%= f.input :date %>

          <%= f.input :is_tournament_open, as: :radio_buttons, collection: [[true, @open], [false, @close]], label_method: :second, value_method: :first, wrapper: :horizontal_collection_inline %>

          <%= f.input :period, as: :radio_buttons, collection: [["morning", @morning], ["afternoon", @afternoon], ["full-day", @fullDay]], label_method: :second, value_method: :first, wrapper: :horizontal_collection_inline %>

          <%= f.input :start_time, as: :time, wrapper: :horizontal_multi_select %>

          <%= f.input :club_id, collection: [[@event.club_id, Club.find(@event.club_id).name]], label_method: :second, value_method: :first, disabled: true %>

          <%= f.input :is_outdoor, as: :radio_buttons, collection: [[true, @outdoor], [false, @indoor]], label_method: :second, value_method: :first, wrapper: :horizontal_collection_inline %>

          <%= f.input :location %>

          <%= f.input :contact %>

          <!-- Categories available for the tournament and set maximal places for each category-->
          <div class="form-row">
            <div class="form-group col-sm-4">
              <%= t "category" %> :
              <br>(<%= t "maxNumberOfTeams" %>)
            </div>
            <div class="form-group col-sm-4">
              <% Category.all.each_with_index do |categorie, i| %>
                <% if @event.categories[categorie.id.to_s]["total_places"].to_i > 0 %>
                <%= "<div class='checkbox'><label><input type='checkbox' name='category-#{categorie.id}' value='true' checked>&nbsp;#{@categories[i]}</label></div>".html_safe %>
                <% else %>
                <%= "<div class='checkbox'><label><input type='checkbox' name='category-#{categorie.id}' value='true'>&nbsp;#{@categories[i]}</label></div>".html_safe %>
                <% end %>
              <% end %>
            </div>
            <div class="form-group col-sm-4">
              <% Category.all.each do |categorie| %>
                <%= "<input type='number' class='form-control form-control-sm mr-1' name='total_places-#{categorie.id}' min='0' max='20' value='#{@event.categories[categorie.id.to_s]["total_places"].to_i}'></textarea>".html_safe %>
              <% end %>
            </div>
          </div>

          <%= f.input :other_informations %>

          <div class="form-group row mb-0">
            <div class="col-sm-9 offset-sm-3">
              <%= f.button :submit, class: "btn-primary" %>
              <%= link_to root_path, class: "btn btn-outline-secondary" do %>
                <%= t 'cancel' %>
              <% end %>
            </div>
            <div class="col-sm-9 offset-sm-3 my-3">
              <%= link_to event_path(@event.id), method: :delete, class: "btn btn-danger" do %>
                <% t 'deleteTournament' %>
              <% end %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>